# Generated by Django 3.1.5 on 2021-01-31 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='create_at',
        ),
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
